name: CurrentConverter
options:
  bundleIdPrefix: com.currentconverter
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "16.0"
packages:
  RealmSwift:
    url: https://github.com/realm/realm-swift
    version: 10.49.0
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    version: 2.9.1
  Mocker:
    url: https://github.com/WeTransfer/Mocker
    version: 3.0.2
  #NetworkManager:
    #path: NetworkManager
targets:
  CurexConverter:
    settings:
        base:
          #SWIFT_ACTIVE_COMPILATION_CONDITIONS: '$(inherited) USING_DELEGATES'
          SWIFT_VERSION: 5.0 # Since GitHub does not have Xcode 16 for now
    type: application
    platform: iOS
    sources: [CurrencyConverter]
    info:
        path: CurrencyConverter/Info.plist
        properties:
          UILaunchStoryboardName: "LaunchScreen" # Launch screen interface file base name
    dependencies:
        - package: RealmSwift
        - package: Swinject
        #- package: NetworkManager
        #- target: NetworkManager
    postCompileScripts:
        - script: "mint run swiftlint"
          name: SwiftLint
  CurexConverter-ObjC:
    settings:
        base:
          SWIFT_VERSION: 5.0
          SWIFT_OBJC_BRIDGING_HEADER: "CurrencyConverter/CurrentConverterApp-Bridging-Header.h"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: '$(inherited) USING_OBJC'
          OTHER_CFLAGS: '$(inherited) -DUSING_OBJC'
    type: application
    platform: iOS
    sources: [CurrencyConverter]
    info:
        path: CurrencyConverter/Info.plist
        properties:
          UILaunchStoryboardName: "LaunchScreen"
    dependencies:
        - package: RealmSwift
        - package: Swinject
    postCompileScripts:
        - script: "mint run swiftlint"
          name: SwiftLint
  CurexConverter-tvOS:
    settings:
        base:
          SWIFT_VERSION: 5.0
          #SWIFT_ACTIVE_COMPILATION_CONDITIONS: '$(inherited) USING_TVOS'
    type: application
    platform: tvOS
    sources: [CurrencyConverter]
    info:
        path: CurrencyConverter/Info.plist
        properties:
          UILaunchStoryboardName: "LaunchScreen" # Launch screen interface file base name
    dependencies:
        - package: RealmSwift
        - package: Swinject
    postCompileScripts:
        - script: "mint run swiftlint"
          name: SwiftLint
  CurexConverterTests:
    type: bundle.unit-test
    platform: iOS
    sources: [CurrentConverterAppTests]
    dependencies:
      - target: CurexConverter
      - package: Mocker
    info:
        path: CurrentConverterAppTests/Info.plist
    postCompileScripts:
        - script: "mint run swiftlint"
          name: SwiftLint
  CurexConverterUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - CurrentConverterAppUITests
      - CurrencyConverter/AccessibilityIdentifiers.swift
    dependencies:
      - target: CurexConverter
    info:
        path: CurrentConverterAppUITests/Info.plist
    postCompileScripts:
        - script: "mint run swiftlint"
          name: SwiftLint

#  NetworkManager:
#    type: framework
#    platform: iOS
#    sources: [NetworkManager]
#    info:
#      path: NetworkManager/Info.plist
