name: CurrentConverter
options:
  bundleIdPrefix: com.currentconverter
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "16.0"
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    version: 5.7.1
targets:
  CurrentConverterApp:
    settings:
      base:
        #SWIFT_ACTIVE_COMPILATION_CONDITIONS: '$(inherited) USING_DELEGATES'
    type: application
    platform: iOS
    sources: [CurrencyConverter]
    info:
      path: CurrencyConverter/Info.plist
    dependencies:
      - package: SnapKit
