name: Currentcies tests

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - feature/ruby

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.1
      - name: Install Mint
        run: brew install mint
      - name: Install Bundler
        run: gem install bundler
      - name: Bundle Install
        run: bundle install
      - name: Build and test
        run: bundle exec fastlane test

