name: Currentcies tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.1
      - name: Setup project
        run: ./setup.sh
      - name: Build and test
        run: xcodebuild test -project CurrentConverter.xcworkspace -scheme CurexConverter -destination "platform=iOS Simulator,OS=18.0,name=iPhone 15"
