name: Currentcies tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.1
      - name: Install Mint
        run: brew install mint
      - name: Generate Xcode project
        run: mint bootstrap && mint run xcodegen
      - name: Build and test
        run: xcodebuild test -project CurrentConverter.xcodeproj -scheme CurrentConverterApp -destination "platform=iOS Simulator,OS=18.0,name=iPhone 15"
